spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/UT
    username: postgres
    password: admin
  mvc:
    pathmatch:
      matching-strategy: ant-path-matcher
authTokens:
  yandex:
    oathToken: AQAAAAALhurcAATuwcZaVwda5UsMiiZoSMfRzDI
    folderId: b1gmkkvlj0attcmkmda4
scheduler:
  yandex:
    intervalMs: 3600000
